name: CI

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline_backend:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [ 16.x ]
        mongodb-version: [ '5.0' ]

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: npm install
        run: npm install

      - name: tests
        run: npm run test

